/-
Vendored verbatim (up to the namespace rename `OAI.Saxl` → `OAI.SaxlOAI` and import paths) from
https://github.com/openai/math, commit adc7f1241b42e322a6451854ab7e4b4c146bf78a,
file lean/OAI/RepresentationTheory/Saxl/BandSupport.lean.  Copyright OpenAI, Apache License 2.0 (see
Saxl/OAI/LICENSE).  NOT written for this repository: see README "Provenance".
-/
import Saxl.OAI.CyclicSector

namespace OAI

noncomputable section

open scoped TensorProduct

namespace SaxlOAI

def stairBandWord (h s : ℕ) : WordSpace (bandSize h s)
    ((staircase (h+s)).colLen 0 * (staircase (h+s)).colLen 0) :=
  wordTensor _ _ _ (bandRowWord h s ⊗ₜ[ℂ] bandColumnWord h s)

def lowPairLetter (h : ℕ) (x : Fin 4) :
    Fin ((staircase (h+2)).colLen 0 * (staircase (h+2)).colLen 0) :=
  finProdFinEquiv (lowLetter h (Path.parts x).1, lowLetter h (Path.parts x).2)

lemma bandColumn_path_eval' (h : ℕ) (w : Fin (2*(h+1)+1) → Fin 2) :
    bandColumnWord h 2 ((lowLetter h ∘ w) ∘ (bandPathEquiv h).symm) =
      PathLayer.rowAlt (h+1) (w ∘ Fin.rev) := by
  have he : (lowLetter h ∘ (w ∘ Fin.rev)) ∘ (bandColumnPathEquiv h).symm =
      (lowLetter h ∘ w) ∘ (bandPathEquiv h).symm := by
    funext i
    simp [bandColumnPathEquiv, Function.comp_def, Fin.revPerm]
  rw [← he, bandColumn_path_eval]

lemma stairBandWord_path_eval (h : ℕ) (w : Fin (2*(h+1)+1) → Fin 4) :
    restrictLetters (lowPairLetter h) (stairBandWord h 2) (w ∘ (bandPathEquiv h).symm) =
      (-1 : ℂ)^(h+1) * Path.bandWord (h+1) w := by
  change wordTensor _ _ _ (bandRowWord h 2 ⊗ₜ[ℂ] bandColumnWord h 2)
    (lowPairLetter h ∘ (w ∘ (bandPathEquiv h).symm)) = _
  rw [wordTensor_tmul]
  have hl : splitLeft (lowPairLetter h ∘ (w ∘ (bandPathEquiv h).symm)) =
      (lowLetter h ∘ (fun i => (Path.parts (w i)).1)) ∘ (bandPathEquiv h).symm := by
    funext i; simp [splitLeft, lowPairLetter]
  have hr : splitRight (lowPairLetter h ∘ (w ∘ (bandPathEquiv h).symm)) =
      (lowLetter h ∘ (fun i => (Path.parts (w i)).2)) ∘ (bandPathEquiv h).symm := by
    funext i; simp [splitRight, lowPairLetter]
  rw [hl,hr,bandRow_path_eval,bandColumn_path_eval']
  exact PathLayer.paired_rowAlt _ w

/- Every Specht shape with at most four rows occurs in the cyclic module
generated by the prescribed two-band vector. -/
theorem twoBand_support (h : ℕ) (hh : 1 ≤ h) (μ : YoungDiagram)
    (t : Tableau (bandSize h 2) μ) (hμ : μ.colLen 0 ≤ 4) :
    ∃ f : Representation.IntertwiningMap (spechtRep t)
      (cyclic (wordRep _ _) (stairBandWord h 2)).toRepresentation, f ≠ 0 := by
  have he : restrictLetters (lowPairLetter h) (stairBandWord h 2) =
      (-1 : ℂ)^(h+1) • (fun w => Path.bandWord (h+1) (w ∘ bandPathEquiv h)) := by
    funext w
    have hw : (w ∘ bandPathEquiv h) ∘ (bandPathEquiv h).symm = w := by funext i; simp
    simpa only [hw,Pi.smul_apply,smul_eq_mul] using stairBandWord_path_eval h (w ∘ bandPathEquiv h)
  have hs := support_relabel (bandPathEquiv h) (Path.bandWord (h+1))
    (fun ν s hν => Path.fourRow_support (h+1) (by omega) ν s hν) μ t hμ
  have hc : cyclic (wordRep (bandSize h 2) 4) (restrictLetters (lowPairLetter h) (stairBandWord h 2)) =
      cyclic (wordRep (bandSize h 2) 4) (fun w => Path.bandWord (h+1) (w ∘ bandPathEquiv h)) := by
    rw [he,cyclic_smul_eq _ _ _ (pow_ne_zero _ (by norm_num))]
  rw [← hc] at hs
  obtain ⟨f,hf⟩ := hs
  exact cyclic_projection_support (restrictLetters (lowPairLetter h)) (stairBandWord h 2) f hf

end SaxlOAI

namespace SaxlOAI

/- Coordinate subrepresentation using only letters with property A. -/
def alphabetSub (n d : ℕ) (A : Fin d → Prop) : Subrepresentation (wordRep n d) where
  toSubmodule :=
    { carrier := {x | ∀ w, (∃ i, ¬ A (w i)) → x w = 0}
      zero_mem' := by intro w hw; rfl
      add_mem' := by intro x y hx hy w hw; change x w+y w=0; rw [hx w hw,hy w hw,add_zero]
      smul_mem' := by intro c x hx w hw; change c*x w=0; rw [hx w hw,mul_zero] }
  apply_mem_toSubmodule g := by
    intro x hx w hw
    obtain ⟨i,hi⟩ := hw
    apply hx (w ∘ g)
    exact ⟨g⁻¹ i, by simpa using hi⟩

lemma alphabetSub_iff {n d : ℕ} (A : Fin d → Prop) (x : WordSpace n d) :
    x ∈ alphabetSub n d A ↔ ∀ w, x w ≠ 0 → ∀ i, A (w i) := by
  change (∀ w, (∃ i, ¬ A (w i)) → x w = 0) ↔ _
  constructor
  · intro h w hw i
    by_contra hn
    exact hw (h w ⟨i,hn⟩)
  · intro h w hw
    by_contra hn
    obtain ⟨i,hi⟩ := hw
    exact hi (h w hn i)

lemma cyclic_alphabet {n d : ℕ} (A : Fin d → Prop) (v : WordSpace n d)
    (hv : v ∈ alphabetSub n d A) (x : WordSpace n d) (hx : x ∈ cyclic (wordRep n d) v) :
    x ∈ alphabetSub n d A := (cyclic_le _ _ _).mpr hv hx

lemma single_mem_alphabet {n d : ℕ} (A : Fin d → Prop) (a : Fin n → Fin d) (ha : ∀ i, A (a i)) :
    (Pi.single a (1:ℂ) : WordSpace n d) ∈ alphabetSub n d A := by
  classical
  intro w hw
  apply Pi.single_eq_of_ne
  intro he
  subst w
  obtain ⟨i,hi⟩ := hw
  exact hi (ha i)

lemma altWord_mem_alphabet {n d : ℕ} (A : Fin d → Prop)
    (G : Subgroup (Equiv.Perm (Fin n))) (a : Fin n → Fin d) (ha : ∀ i, A (a i)) :
    altWord G a ∈ alphabetSub n d A := by
  classical
  unfold altWord
  apply Submodule.sum_mem
  intro g hg
  apply Submodule.smul_mem
  exact (alphabetSub n d A).apply_mem_toSubmodule g.val (single_mem_alphabet A a ha)

lemma letterLift_mem_alphabet {n d D : ℕ} (A : Fin D → Prop)
    (φ : Fin d → Fin D) (hφ : ∀ i, A (φ i)) (x : WordSpace n d) :
    letterLift φ x ∈ alphabetSub n D A := by
  classical
  intro w hw
  obtain ⟨i,hi⟩ := hw
  change (∑ a, x a * ∏ j, (if φ (a j) = w j then (1:ℂ) else 0)) = 0
  apply Finset.sum_eq_zero
  intro a ha
  apply mul_eq_zero_of_right
  apply Finset.prod_eq_zero (Finset.mem_univ i)
  exact ite_eq_right (fun hh : φ (a i) = w i => hi (hh ▸ hφ (a i)))

lemma letterLift_eval {n d D : ℕ} (φ : Fin d → Fin D) (hφ : Function.Injective φ)
    (x : WordSpace n d) (w : Fin n → Fin d) : letterLift φ x (φ ∘ w) = x w := by
  classical
  change (∑ a, x a * ∏ i, (if φ (a i) = φ (w i) then (1:ℂ) else 0)) = x w
  rw [Finset.sum_eq_single w]
  · simp
  · intro a ha haw
    apply mul_eq_zero_of_right
    obtain ⟨i,hi⟩ : ∃ i, a i ≠ w i := by by_contra hh; push Not at hh; exact haw (funext hh)
    apply Finset.prod_eq_zero (Finset.mem_univ i)
    exact ite_eq_right (fun hh => hi (hφ hh))
  · simp

lemma letterLift_injective {n d D : ℕ} (φ : Fin d → Fin D) (hφ : Function.Injective φ) :
    Function.Injective (letterLift (n := n) φ) := by
  intro x y hxy
  funext w
  have hh := congrFun hxy (φ ∘ w)
  simpa only [letterLift_eval φ hφ] using hh

def pairLift {n d D : ℕ} (φ : Fin d → Fin D) :
    Representation.IntertwiningMap (wordRep n (d*d)) (wordRep n (D*D)) :=
  (wordTensorIntertwiner _ _ _).comp (((letterLift φ).tensor (letterLift φ)).comp
    ((wordTensorIntertwiner n d d).ofBijective (wordTensor n d d).bijective).symm.toIntertwiningMap)

lemma pairLift_wordTensor {n d D : ℕ} (φ : Fin d → Fin D) (x y : WordSpace n d) :
    pairLift φ (wordTensor n d d (x ⊗ₜ[ℂ] y)) =
      wordTensor n D D (letterLift φ x ⊗ₜ[ℂ] letterLift φ y) := by
  let E := (wordTensorIntertwiner n d d).ofBijective (wordTensor n d d).bijective
  change wordTensor n D D (((letterLift φ).tensor (letterLift φ)) (E.symm (E (x ⊗ₜ[ℂ] y)))) = _
  rw [E.symm_apply_apply]
  rfl

lemma pairLift_injective {n d D : ℕ} (φ : Fin d → Fin D) (hφ : Function.Injective φ) :
    Function.Injective (pairLift (n := n) φ) := by
  apply (wordTensor n D D).injective.comp
  apply (TensorProduct.map_injective_of_flat_flat _ _ (letterLift_injective φ hφ) (letterLift_injective φ hφ)).comp
  exact ((wordTensorIntertwiner n d d).ofBijective (wordTensor n d d).bijective).symm.injective

lemma pairWord_mem_alphabetLeft {n d : ℕ} (A : Fin d → Prop)
    (x y : WordSpace n d) (hx : x ∈ alphabetSub n d A) :
    wordTensor n d d (x ⊗ₜ[ℂ] y) ∈
      alphabetSub n (d*d) (fun a => A (finProdFinEquiv.symm a).1) := by
  apply (alphabetSub_iff _ _).mpr
  intro w hw i
  rw [wordTensor_tmul] at hw
  exact (alphabetSub_iff A x).mp hx (splitLeft w) ((mul_ne_zero_iff.mp hw).1) i



def shiftedStairWord (h s : ℕ) := pairLift (highLetter h s) (staircaseWord h)

lemma highLetter_injective (h s : ℕ) : Function.Injective (highLetter h s) := by
  intro a b hab
  apply Fin.ext
  have := congrArg Fin.val hab
  dsimp [highLetter] at this
  omega

lemma shiftedStairWord_support (h s : ℕ) (μ : YoungDiagram) (t : Tableau (staircase h).card μ)
    (f : Representation.IntertwiningMap (spechtRep t) (staircaseCyclic h).toRepresentation)
    (hf : f ≠ 0) :
    ∃ F : Representation.IntertwiningMap (spechtRep t)
      (cyclic (wordRep _ _) (shiftedStairWord h s)).toRepresentation, F ≠ 0 := by
  let F := (cyclicMap (pairLift (highLetter h s)) (staircaseWord h)).comp f
  refine ⟨F, ?_⟩
  intro hz
  apply hf
  apply Representation.IntertwiningMap.ext
  apply LinearMap.ext
  intro x
  apply Subtype.ext
  apply pairLift_injective (highLetter h s) (highLetter_injective h s)
  have hh := congrArg (fun l => (l x).val) hz
  exact hh.trans (map_zero _).symm

lemma shiftedStairWord_alphabet (h s : ℕ) :
    shiftedStairWord h s ∈ alphabetSub _ _ (fun a => s ≤ ((finProdFinEquiv.symm a).1).val) := by
  unfold shiftedStairWord staircaseWord
  rw [pairLift_wordTensor]
  apply pairWord_mem_alphabetLeft (fun a => s ≤ a.val)
  apply letterLift_mem_alphabet
  intro i
  dsimp [highLetter]
  omega

lemma bandRowWord_alphabet (h s : ℕ) :
    bandRowWord h s ∈ alphabetSub _ _ (fun a => ¬s ≤ a.val) := by
  apply altWord_mem_alphabet
  intro j
  have hb := (bandTableau_bounds h s j).1
  have hr := rotateRow_high h s (bandTableau h s j)
  have hh : ¬ s ≤ (rotateRow h s (bandTableau h s j)).val.2 :=
    fun hh => (Nat.not_lt.mpr hb) (hr.mp hh)
  simpa [rightWord,rowWord,stairRowTableau,rotateRowPositions,bandTableau,staircaseSwap] using hh

lemma stairBandWord_alphabet (h s : ℕ) :
    stairBandWord h s ∈ alphabetSub _ _ (fun a => ¬ s ≤ ((finProdFinEquiv.symm a).1).val) := by
  apply pairWord_mem_alphabetLeft (fun a => ¬s ≤ a.val)
  exact bandRowWord_alphabet h s

/- The actual same-high image factors as the smaller Specht tensor cyclic
vector and the exact retained band vector on independent position blocks. -/
theorem staircase_cut_factor (h s : ℕ) :
    sameHighProjection _ _ _ s (staircaseWord (h+s)) =
      positionProduct (cutPositions h s) (shiftedStairWord h s) (stairBandWord h s) := by
  rw [staircase_cut_layers,cutRowWord_factor,cutColumnWord_factor]
  unfold shiftedStairWord staircaseWord
  rw [pairLift_wordTensor]
  ext w
  simp only [wordTensor_tmul, stairBandWord, positionProduct]
  exact mul_mul_mul_comm _ _ _ _



lemma bandColumnWord_alphabet (h s : ℕ) :
    bandColumnWord h s ∈ alphabetSub _ _ (fun a => ¬s ≤ a.val) := by
  apply altWord_mem_alphabet
  intro j
  have hb := (bandTableau_bounds h s j).1
  have hr := rotateColumn_high h s (bandTableau h s j)
  have hh : ¬ s ≤ (rotateColumn h s (bandTableau h s j)).val.1 :=
    fun hh => (Nat.not_lt.mpr hb) (hr.mp hh)
  simpa [rightWord,rowWord,rotateColumnPositions,bandTableau] using hh

lemma alphabet_small_invariant {n d : ℕ} (A : Fin d → Prop)
    (hA : ∀ a b, A a → A b → a = b) (x : WordSpace n d)
    (hx : x ∈ alphabetSub n d A) (g : Equiv.Perm (Fin n)) : wordRep n d g x = x := by
  ext w
  change x (w ∘ g) = x w
  have he : (∀ i, A (w i)) → w ∘ g = w := by
    intro h
    funext i
    exact hA _ _ (h (g i)) (h i)
  by_cases h : ∀ i, A (w i)
  · rw [he h]
  · have hz : x w = 0 := by
      by_contra hn
      exact h ((alphabetSub_iff A x).mp hx w hn)
    rw [hz]
    by_contra hn
    have hh := (alphabetSub_iff A x).mp hx (w ∘ g) hn
    apply h
    intro i
    simpa using hh (g⁻¹ i)

lemma oneBand_invariant (h : ℕ) (g : Equiv.Perm (Fin (bandSize h 1))) :
    wordRep _ _ g (stairBandWord h 1) = stairBandWord h 1 := by
  have ha (a b : Fin ((staircase (h+1)).colLen 0)) (ha : ¬1 ≤ a.val) (hb : ¬1 ≤ b.val) : a = b := by
    apply Fin.ext; omega
  have hr := alphabet_small_invariant (fun a => ¬1 ≤ a.val) ha _ (bandRowWord_alphabet h 1) g
  have hc := alphabet_small_invariant (fun a => ¬1 ≤ a.val) ha _ (bandColumnWord_alphabet h 1) g
  ext w
  change stairBandWord h 1 (w ∘ g) = stairBandWord h 1 w
  simp only [stairBandWord,wordTensor_tmul]
  exact congrArg₂ (fun x y : ℂ => x*y) (congrFun hr (splitLeft w)) (congrFun hc (splitRight w))

lemma stairBandWord_ne_zero (h s : ℕ) : stairBandWord h s ≠ 0 := by
  intro hz
  apply staircase_projected_ne_zero h s
  rw [staircase_cut_factor,hz]
  ext w
  change _ * 0 = 0
  exact mul_zero _

lemma oneRow_support_invariant {n d : ℕ} (μ : YoungDiagram) (t : Tableau n μ)
    (hμ : μ.colLen 0 ≤ 1) (u : WordSpace n d) (hu : u ≠ 0)
    (he : ∀ g, wordRep n d g u = u) :
    ∃ f : Representation.IntertwiningMap (spechtRep t)
      (cyclic (wordRep n d) u).toRepresentation, f ≠ 0 := by
  have hw (g : Equiv.Perm (Fin n)) : rowWord t ∘ g = rowWord t := by
    funext i
    apply Fin.ext
    have h₁ := (rowWord t (g i)).isLt
    have h₂ := (rowWord t i).isLt
    omega
  let F : Specht t →ₗ[ℂ] (cyclic (wordRep n d) u).toSubmodule :=
    { toFun := fun x => ⟨x.val (rowWord t) • u, Submodule.smul_mem _ _ (mem_cyclic _ _)⟩
      map_add' := by intro x y; apply Subtype.ext; exact add_smul _ _ _
      map_smul' := by intro c x; apply Subtype.ext; exact mul_smul _ _ _ }
  let f : Representation.IntertwiningMap (spechtRep t) (cyclic (wordRep n d) u).toRepresentation :=
    { toLinearMap := F
      isIntertwining' := by
        intro g
        apply LinearMap.ext
        intro x
        apply Subtype.ext
        change x.val (rowWord t ∘ g) • u = wordRep n d g (x.val (rowWord t) • u)
        rw [hw,map_smul,he] }
  refine ⟨f, ?_⟩
  intro hz
  have hh := congrArg (fun f => (f ⟨polytabloid t,mem_cyclic _ _⟩).val) hz
  change polytabloid t (rowWord t) • u = 0 at hh
  rw [polytabloid_rowWord,one_smul] at hh
  exact hu hh

/- The width-one band is the genuine trivial constituent required by Pieri. -/
theorem oneBand_support (h : ℕ) (μ : YoungDiagram) (t : Tableau (bandSize h 1) μ)
    (hμ : μ.colLen 0 ≤ 1) :
    ∃ f : Representation.IntertwiningMap (spechtRep t)
      (cyclic (wordRep _ _) (stairBandWord h 1)).toRepresentation, f ≠ 0 :=
  oneRow_support_invariant μ t hμ _ (stairBandWord_ne_zero h 1) (oneBand_invariant h)

end SaxlOAI

end

end OAI
